---
name: Assist Autocorrect
version: dev
slug: assist-autocorrect
description: Simple & Free Autocomplete for Assist
url: https://github.com/matt-hurd/ha-autocorrect/tree/main/ha-autocorrect
init: false
arch:
  - aarch64
  - amd64
map:
  - ssl
ports:
  9000/tcp: 2971
ports_description:
  9000/tcp: API
image: "ghcr.io/matt-hurd/{arch}-ha-autocorrect"
options:
  typesense_host: 127.0.0.1
  typesense_port: 8108
schema:
  typesense_host: string
  typesense_port: integer