---
name: Typesense
version: dev
slug: typesense
description: Typesense
url: https://github.com/matt-hurd/ha-autocorrect/tree/main/typesense
init: false
arch:
  - aarch64
  - amd64
ports:
  8108/tcp: 8108
ports_description:
  8108/tcp: API
image: "ghcr.io/matt-hurd/{arch}-typesense"