---
name: Assist Autocorrect
version: dev
slug: autocorrect
description: Simple & Free Autocomplete for Assist
url: https://github.com/matt-hurd/ha-autocorrect/tree/main/autocorrect
init: false
arch:
  - aarch64
  - amd64
homeassistant_api: true
hassio_api: true
ports:
  9000/tcp: 2971
ports_description:
  9000/tcp: API
options:
  typesense_host: local_typesense
  typesense_port: 8108
schema:
  typesense_host: str
  typesense_port: int
